stages:
- name: "123"
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/app:v1
      registry: 127.0.0.1:34557
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/app:v2
      registry: 127.0.0.1:34557
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
